import { mkdir, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const scriptDirectory = path.dirname(fileURLToPath(import.meta.url))
const partDirectory = path.resolve(scriptDirectory, '..')
const pluginPath = path.resolve(partDirectory, 'plugins', 'autoresearch.mjs').replaceAll('\\', '/')
const outputPath = path.resolve(partDirectory, 'patches', 'part-c.generated.cordis.yml')

const patch = `# Generated by scripts/generate-patch.mjs. Do not edit manually.\n#\n# Apply this overlay to the official DeepSeek Harness standard preset.\n- insert:\n    - id: part-c-autoresearch-ml\n      name: "${pluginPath}"\n`

await mkdir(path.dirname(outputPath), { recursive: true })
await writeFile(outputPath, patch, 'utf8')
console.log(`Generated ${outputPath}`)
