import { mkdir, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const partBRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const patchDirectory = path.join(partBRoot, 'patches')
const patchPath = path.join(patchDirectory, 'part-b.generated.cordis.yml')

// The official guide requires local plugin module paths to be absolute. Use
// forward slashes so the generated YAML works on both Windows and Unix hosts.
const portable = value => value.replaceAll('\\', '/')
const sessionInspector = portable(path.join(partBRoot, 'plugins', 'session-inspector.mjs'))
const promptLinter = portable(path.join(partBRoot, 'plugins', 'prompt-linter.mjs'))

const content = `# Generated by scripts/generate-patch.mjs. Do not edit manually.\n#\n# The standard DeepSeek Harness preset already supplies five official plugins:\n# tool-fs, tool-fs-search, tool-todo, tool-web, and tool-ask-user.\n# This overlay adds the two Part B plugins implemented from scratch.\n- insert:\n    - id: part-b-session-inspector\n      name: ${JSON.stringify(sessionInspector)}\n    - id: part-b-prompt-linter\n      name: ${JSON.stringify(promptLinter)}\n`

await mkdir(patchDirectory, { recursive: true })
await writeFile(patchPath, content, 'utf8')
console.log(`Generated ${patchPath}`)
